name       : ksystemlog
version    : 20.04.0
release    : 3
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.0/src/ksystemlog-20.04.0.tar.xz : a3da8b9132e549b4d543de89b6be573eee164e55cfccb7bc99dfb1d4e0f3b66b
homepage   : https://kde.org/applications/system/ksystemlog/
license    : GPL-2.0-only
component  : system.utils
summary    : System log viewer tool
description: |
    System log viewer tool
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - karchive-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kio-devel
    - ktextwidgets-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
