name       : ksystemlog
version    : 21.04.3
release    : 19
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.3/src/ksystemlog-21.04.3.tar.xz : 70e8dbed3b88614e33115ad198c98edf3300f9e5f934528589a34796121d9587
homepage   : https://kde.org/applications/system/ksystemlog/
license    : GPL-2.0-only
component  : system.utils
summary    : System log viewer tool
description: |
    System log viewer tool
builddeps  :
    - karchive-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kio-devel
    - ktextwidgets-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove docs
    rm -rf $installdir/usr/share/doc
