name       : ksystemlog
version    : 23.04.2
release    : 36
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.2/src/ksystemlog-23.04.2.tar.xz : 10040138c02ed49433c77e82ac82349f2d3885c0fda2e264ca4aa0373482af8a
homepage   : https://kde.org/applications/system/ksystemlog/
license    : GPL-2.0-only
component  : system.utils
summary    : System log viewer tool
description: |
    System log viewer tool
builddeps  :
    - karchive-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kio-devel
    - ktextwidgets-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove docs
    rm -rf $installdir/usr/share/doc

    # Fix appstream processing
    install -Dm00644 $workdir/logo.png $installdir/usr/share/pixmaps/utilities-log-viewer.png
