name       : ksystemlog
version    : 20.04.2
release    : 5
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.2/src/ksystemlog-20.04.2.tar.xz : 097796719fa8b503cffb0a036e2f8d4152acaf3c8ad8b4ae721b528a2fa6dceb
homepage   : https://kde.org/applications/system/ksystemlog/
license    : GPL-2.0-only
component  : system.utils
summary    : System log viewer tool
description: |
    System log viewer tool
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - karchive-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kio-devel
    - ktextwidgets-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |-
    %ninja_install

    # remove docs
    rm -rf $installdir/usr/share/doc
