name       : ksystemlog
version    : 22.04.0
release    : 27
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.0/src/ksystemlog-22.04.0.tar.xz : 25525e28756928ddb014ccec6f352c7378473ad417971608989818484b2847a4
homepage   : https://kde.org/applications/system/ksystemlog/
license    : GPL-2.0-only
component  : system.utils
summary    : System log viewer tool
description: |
    System log viewer tool
builddeps  :
    - karchive-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kio-devel
    - ktextwidgets-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove docs
    rm -rf $installdir/usr/share/doc
