name       : ksystemlog
version    : 20.08.3
release    : 10
source     :
    - https://cdn.download.kde.org/stable/release-service/20.08.3/src/ksystemlog-20.08.3.tar.xz : 2285996b8b1447b94d5d4011a4f9e9d117702f8c4fe873fb5d914d486c15cc85
homepage   : https://kde.org/applications/system/ksystemlog/
license    : GPL-2.0-only
component  : system.utils
summary    : System log viewer tool
description: |
    System log viewer tool
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - karchive-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kio-devel
    - ktextwidgets-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |-
    %ninja_install

    # remove docs
    rm -rf $installdir/usr/share/doc
