name       : ksystemlog
version    : 23.04.0
release    : 33
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.0/src/ksystemlog-23.04.0.tar.xz : 0cf79c529641a087c83a3f6249ec1b9a493c5a28d954478ca8ddd5c16e8e7f42
homepage   : https://kde.org/applications/system/ksystemlog/
license    : GPL-2.0-only
component  : system.utils
summary    : System log viewer tool
description: |
    System log viewer tool
builddeps  :
    - karchive-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kio-devel
    - ktextwidgets-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove docs
    rm -rf $installdir/usr/share/doc
