name       : ksystemlog
version    : 21.12.0
release    : 24
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.0/src/ksystemlog-21.12.0.tar.xz : 4f506b5227bfb2081096d3f7b505e85f8fc58a8ae5bcb102ab61bbffcc5cb806
homepage   : https://kde.org/applications/system/ksystemlog/
license    : GPL-2.0-only
component  : system.utils
summary    : System log viewer tool
description: |
    System log viewer tool
builddeps  :
    - karchive-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kio-devel
    - ktextwidgets-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove docs
    rm -rf $installdir/usr/share/doc
